### ISSUE TITLE
Lepení motorů do podvozku

### ISSUE THREAD

**Issue by MarPta** [RoboticsBrno/mickoflus.cz#10]
Krok "Zalep motory do podvozku. Dej si pozor na to, ať výstupek na motoru vždy směřuje vně podvozku!" je velmi matoucí a děti lepí žlutý plast motorů k spodní desce podvozku. Je třeba zdůraznit, že se lepí pouze překližkové díly do spodního dílu podvozku a na plast se lepidlo nenanáší.

**Comment by yaqwsx** [comment]
Vyřešeno.

**Comment by JarekParal** [comment]
Jak vyřešeno? @yaqwsx

**Comment by yaqwsx** [comment]
Nepamatuji si, ale podle data posledního komentáře jsem to opravil už na
táboře a issue jsem zapomněl zavřít.

út 5. 2. 2019 10:53 odesílatel Jaroslav Páral <notifications@github.com>
napsal:

**Comment by JarekParal** [comment]
Ale na webu je pořád stejný popisek:
![image](https://user-images.githubusercontent.com/6726556/52266638-345d9880-2937-11e9-8ee1-20d19fa60003.png)

**Comment by JarekParal** [comment]
Ok, sorry :-).

**Comment by MarPta** [comment]
Ahoj. Podle mě stojí za to zdůraznit* nelepení *plastové převodovky motoru
větou: "Lep pouze dřevo na dřevo" nebo "Zanech žlutou převodovku motoru bez
lepidla". Mluví ze mě pár dní stará zkušenost z Hradce Králové, kde se
montoval RoboTommy :)
Martin

út 5. 2. 2019 v 12:31 odesílatel Jaroslav Páral <notifications@github.com>
napsal:
