### ISSUE TITLE
V návode je časť textu pred obrázkami a na mobilnej verzii to potom nie je vidno.

### ISSUE THREAD

**Issue by MatejMa2ur** [RoboticsBrno/mickoflus.cz#28]
Niektoré texty nie v modrých rámčekoch ale na bielom sú pred 0 zarážkou a potom to na mobilnej verzii nie je vidno.

**Comment by MatejMa2ur** [comment]
Nenašiel som presne, kde som to myslel, možno už to tam nie je ale všimol som si toto, nijako som to nevedel zobraziť, nešlo zmenšiť, zväčšiť ani posunúť:

![screenshot_20190131-122713](https://user-images.githubusercontent.com/41269745/52051639-6dbb9000-2554-11e9-9b64-78b15976be0b.png)
![Uploading Screenshot_20190131-122803.png…]()

**Comment by JarekParal** [comment]
Duplicated: https://github.com/RoboticsBrno/mickoflus.cz/issues/32
